quickstart: rewrite with widgets
40ants/weblocks pull request #14
Opened 2018-06-17 18:56 UTC by vindarel

I suggest to rewrite the quickstart with widgets. It was needed, so why not teach the heart of Weblocks right away. And there are no large code blocks anymore.

I kept the progression with first a list of tasks, then adding one, then toggle its state.

I added links to Practical CL and the Cookbook to get familiar with CLOS and databases.

I find it amazingly simple how we just need to write a render function for our widgets to get started. Still hooked :)

2018-06-18 18:24 UTC, svetlyak40wt requested changes
Hi, Vindarel!

Thank you for contribution. I found few ways how to improve it before merge. Please, read comments in the code.

By the way, I've set up a Travis to build documentation automatically when pull requests are merged into the `reblocks` branch. That way docs at http://40ants.com/weblocks/ will be always up to date.

2018-06-18 18:24 UTC, svetlyak40wt commented on docs/source/quickstart.lisp
>  (weblocks/server:start :port *port*)
Actually, `weblocks/server:start` should also start all apps by default.

2018-06-18 18:24 UTC, svetlyak40wt commented on docs/source/quickstart.lisp
> +    (format stream "~a, done ? ~a" (title task) (done task))))
It is better to not clutter quickstart with unnecessary method. Why did you decide to add a `print-object` here?

2018-06-18 18:24 UTC, svetlyak40wt commented on docs/source/quickstart.lisp
> +(defvar *task-1* (make-instance 'task :title "Make my first Weblocks app"))
Does this variable make sense? I see you are using it to demonstrate some concepts in the documentation, but here in lisp file it is not used.

2018-06-18 18:24 UTC, svetlyak40wt commented on docs/source/quickstart.lisp
> +  "Our root widget.")
This is a bad to have such global variable, because it is not threadsafe to make `setf *root*` later.

Please, remove it and make `weblocks/session:init` just return a root widget. Also, you can add `make-tasks-list` function, which can be used like this:

```lisp
(make-task-list "Make my first Weblocks app"
                "Deploy it somewhere"
                "Have a profit")
```

2018-06-18 18:24 UTC, svetlyak40wt commented on docs/source/quickstart.lisp
> +  (update *root*))
Originally, `add-task` was a closure to catch widget variable. This allowed to not use global variables.

2018-06-19 11:21 UTC, vindarel commented on docs/source/quickstart.lisp
> +  (update *root*))
Hope I fixed it with

```
              (flet ((add-task (&key title &allow-other-keys)
                       (push (make-task :title title)
                             (tasks (weblocks/widgets/root:get)))
                       (update (weblocks/widgets/root:get))))
```

So is it the same for the toggle function, which updates one task ? I fear to have a big pile of functions in a big render method.

```
    TODO> (defmethod toggle ((task task))
            (setf (done task)
                  (if (done task)
                      nil
                      t))
            (update task))
```

2018-06-21 17:44 UTC, vindarel commented
up (in case you didn't notice the commit)

2018-06-23 19:40 UTC, svetlyak40wt approved these changes

2018-06-23 19:40 UTC, svetlyak40wt commented
Now it looks good! Thank you!

2018-06-23 19:40 UTC, merged

2018-06-23 19:52 UTC, svetlyak40wt commented
Documentation was published automatically.

But I have to fix hyperlinks, you forgot whitespaces. Look at the commit https://github.com/40ants/weblocks/commit/9896fdfe62911f2e9d39d37bb02c63bb473e108c

2018-06-23 20:25 UTC, vindarel commented
Yay :)

ok, saw the fixes (I had tried with a pandoc transform though).